Fail trigger_test_upload when pipeline_id is null.

diff --git a/.gitlab/ci/content-ci/ci/.gitlab-ci.on-push.yml b/.gitlab/ci/content-ci/ci/.gitlab-ci.on-push.yml
--- a/.gitlab/ci/content-ci/ci/.gitlab-ci.on-push.yml
+++ b/.gitlab/ci/content-ci/ci/.gitlab-ci.on-push.yml
@@ -909,13 +909,18 @@ test-upload-flow:
     - section_start "Trigger Test Upload Flow On Testing Branch"
     # retry mechanism for trigger upload pipeline in case it failed because of gitlab connectivity issues.
     - for _ in {1..3}; do
-    -   export pipeline_id=$(./Utils/trigger_test_upload_flow.sh -ct "${GITLAB_SVC_USER_TOKEN}" -b "${BRANCH}" -dz | jq .id)
+    -   export response=$(./Utils/trigger_test_upload_flow.sh -ct "${GITLAB_SVC_USER_TOKEN}" -b "${BRANCH}" -dz)
+    -   export pipeline_id=$(echo $response | jq .id)
     -   if [ "${pipeline_id}" != "null" ] && [ "${pipeline_id}" != \"\" ]; then
     -     break
     -   fi
     -   echo "Sleeping for 10 seconds before retrying"
     -   sleep 10
     - done
+    - if [ "${pipeline_id}" == "null" ]; then
+    -   echo "Encountered an error when attempting to trigger upload pipeline, received pipeline_id=null, with response = $response"
+    -   exit 1
+    - fi
     - echo "Successful triggered test upload - ${CI_SERVER_URL}/${CI_PROJECT_NAMESPACE}/content/-/pipelines/$pipeline_id"
     - echo "${pipeline_id}" > "${ARTIFACTS_FOLDER}/test_upload_flow_pipeline_id.txt"
     - section_end "Trigger Test Upload Flow On Testing Branch"
