Consider tags when cloning repos

diff --git a/.gitlab/ci/content-ci/ci/.gitlab-ci.global.yml b/.gitlab/ci/content-ci/ci/.gitlab-ci.global.yml
--- a/.gitlab/ci/content-ci/ci/.gitlab-ci.global.yml
+++ b/.gitlab/ci/content-ci/ci/.gitlab-ci.global.yml
@@ -82,12 +82,12 @@
       local sleep_time=${7:-10}  # default sleep time is 10 seconds.
       local exit_code=0
       local i=1
-      echo -e "${PURPLE}Checking if repository project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name} already exists in ${CI_PROJECT_DIR}/artifacts/repositories/${repo_name}${NC}"
+      echo -e "${PURPLE}Checking if repository repository:${repo_name}, project namespace:${CI_PROJECT_NAMESPACE} already exists in ${CI_PROJECT_DIR}/artifacts/repositories/${repo_name}${NC}"
       if [ -d "${CI_PROJECT_DIR}/artifacts/repositories/${repo_name}" ]; then
         echo -e "${GREEN}Repository ${repo_name} already exists, no need to clone it again${NC}"
         return 0
       fi
-      echo -e "${PURPLE}Cloning project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name} from ${host} branch:${branch} with ${retry_count} retries${NC}"
+      echo -e "${PURPLE}Cloning repository:${repo_name}, project namespace:${CI_PROJECT_NAMESPACE} from ${host} branch:${branch} with ${retry_count} retries${NC}"
       if [ -z "${user}" ] && [ -z "${token}" ]; then
         user_info=""
       else
@@ -96,12 +96,12 @@
       fi
       pushd "${CI_PROJECT_DIR}/artifacts/repositories" || exit 1
       for ((i=1; i <= retry_count; i++)); do
-        git clone --depth=1 "https://${user_info}${host}/${CI_PROJECT_NAMESPACE}/${repo_name}.git" --branch "${branch}" && exit_code=0 && break || exit_code=$?
+        git -c advice.detachedHead=false clone --depth=1 "https://${user_info}${host}/${CI_PROJECT_NAMESPACE}/${repo_name}.git" --branch "${branch}" && exit_code=0 && break || exit_code=$?
         if [ ${i} -ne "${retry_count}" ]; then
-          echo -e "${YELLOW}Failed to clone project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name} with branch:${branch}, exit code:${exit_code}, sleeping for ${sleep_time} seconds and trying again${NC}"
+          echo -e "${YELLOW}Failed to clone repository:${repo_name}, with branch:${branch}, project namespace:${CI_PROJECT_NAMESPACE}, exit code:${exit_code}, sleeping for ${sleep_time} seconds and trying again${NC}"
           sleep "${sleep_time}"
         else
-          echo -e "${RED}Failed to clone project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name} with branch:${branch}, exit code:${exit_code}, exhausted all ${retry_count} retries${NC}"
+          echo -e "${RED}Failed to clone repository:${repo_name} with branch:${branch}, project namespace:${CI_PROJECT_NAMESPACE}, exit code:${exit_code}, exhausted all ${retry_count} retries${NC}"
           break
         fi
       done
@@ -120,41 +120,61 @@
       local fallback_branch="${8:-master}"
 
       # Check if branch exists in the repository.
-      echo -e "${PURPLE}Checking if branch ${branch} exists in project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name}${NC}"
+      echo -e "${PURPLE}Checking if branch/tag ${branch} exists in repository:${repo_name}, project namespace:${CI_PROJECT_NAMESPACE}${NC}"
       if [ -z "${user}" ] && [ -z "${token}" ]; then
         user_info=""
       else
         # If either user or token is not empty, then we need to add them to the url.
         user_info="${user}:${token}@"
       fi
-      git ls-remote --exit-code --quiet --heads "https://${user_info}${host}/${CI_PROJECT_NAMESPACE}/${repo_name}.git" "refs/heads/${branch}" 1>/dev/null 2>&1
-      local branch_exists=$?
+      local tag_exists
+      local branch_type="branch"
+      if [[ ${branch} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "branch ${branch} is formatted like a version (v0.0.0), checking for a matching tag"
+          git ls-remote --exit-code --quiet --tags "https://${user_info}${host}/${CI_PROJECT_NAMESPACE}/${repo_name}.git" "${branch}" 1>/dev/null 2>&1
+          tag_exists=$?
+          if [[ "${tag_exists}" -ne 0 ]]; then
+            echo -e "${PURPLE}Could not find a tag called ${branch}${NC}"
+          else
+            branch_type="tag"
+            echo -e "${GREEN}Found a tag called ${branch}${NC}"
+          fi
+      else
+          echo "branch ${branch} is not formatted like a version (v0.0.0), skipping tag check"
+          tag_exists=-1 # default, for when the branch isn't version-like named
+      fi
 
-      if [ "${branch_exists}" -ne 0 ]; then
-        echo -e "${YELLOW}Branch ${branch} does not exist in project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name}, defaulting to ${fallback_branch}${NC}"
+      if [[ "${tag_exists}" -ne 0 ]]; then
+          echo "Searching for a branch called ${branch}"
+          git ls-remote --exit-code --quiet --heads "https://${user_info}${host}/${CI_PROJECT_NAMESPACE}/${repo_name}.git" "${branch}" 1>/dev/null 2>&1
+          local branch_exists=$?
+      fi
+
+      if [[ "${tag_exists}" -ne 0 ]] && [[ "${branch_exists}" -ne 0 ]]; then
+        echo -e "${YELLOW}branch/tag:${branch} does not exist in repository:${repo_name}, project namespace:${CI_PROJECT_NAMESPACE}, defaulting to ${fallback_branch}${NC}"
         local exit_code=1
       else
-        echo -e "${GREEN}Branch ${branch} exists in project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name}, trying to clone${NC}"
+        echo -e "${GREEN}${branch_type}:${branch} exists in repository:${repo_name}, project namespace:${CI_PROJECT_NAMESPACE}, trying to clone${NC}"
         clone_repository "${host}" "${user}" "${token}" "${repo_name}" "${branch}" "${retry_count}" "${sleep_time}"
         local exit_code=$?
         if [ "${exit_code}" -ne 0 ]; then
-          echo -e "${YELLOW}Failed to clone project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name} with branch:${branch}, exit code:${exit_code}${NC}"
+          echo -e "${YELLOW}Failed to clone repository:${repo_name}, project namespace:${CI_PROJECT_NAMESPACE} with ${branch_type}:${branch}, exit code:${exit_code}${NC}"
         fi
       fi
       if [ "${exit_code}" -ne 0 ]; then
         # Trying to clone from fallback branch.
-        echo -e "${PURPLE}Trying to clone  project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name} with fallback branch ${fallback_branch}!${NC}"
+        echo -e "${PURPLE}Trying to clone repository:${repo_name}, project namespace:${CI_PROJECT_NAMESPACE} with fallback branch ${fallback_branch}!${NC}"
         clone_repository "${host}" "${user}" "${token}" "${repo_name}" "${fallback_branch}" "${retry_count}" "${sleep_time}"
         local exit_code=$?
         if [ ${exit_code} -ne 0 ]; then
-          echo -e "${RED}ERROR: Failed to clone project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name} with fallback branch:${fallback_branch}, exit code:${exit_code}, exiting!${NC}"
+          echo -e "${RED}ERROR: Failed to clone repository:${repo_name}, project namespace:${CI_PROJECT_NAMESPACE} with fallback branch:${fallback_branch}, exit code:${exit_code}, exiting!${NC}"
           exit ${exit_code}
         else
-          echo -e "${GREEN}Successfully cloned project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name} with fallback branch:${fallback_branch}${NC}"
+          echo -e "${GREEN}Successfully cloned repository:${repo_name}, project namespace:${CI_PROJECT_NAMESPACE} with fallback branch:${fallback_branch}${NC}"
           return 0
         fi
       else
-        echo -e "${GREEN}Successfully cloned project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name} with branch:${branch}${NC}"
+        echo -e "${GREEN}Successfully cloned repository:${repo_name}, project namespace:${CI_PROJECT_NAMESPACE} with branch:${branch}${NC}"
         return 0
       fi
     }
@@ -171,7 +191,7 @@
       SEARCHED_BRANCH_NAME_CONTENT_TEST_CONF="${CI_COMMIT_REF_NAME}"
     fi
 
-    if [[ "${CURRENT_BRANCH_NAME}" == "master" ]]; then
+    if [[ "${CURRENT_BRANCH_NAME}" == "master" ]] || [[ ${CURRENT_BRANCH_NAME} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
       echo "Getting infra with branch:${CURRENT_BRANCH_NAME}"
       echo -e "${BLUE}NOTE: If you want to run the build on a specific branch in infra,\nYou need to replace the environment variable INFRA_BRANCH in the .gitlab-ci.yml file\nWith the name of the branch that exists in infra.${NC}"
     else
