CIAC-11078  Move any configuration file outside infra repository

diff --git a/.gitlab/ci/global.yml b/.gitlab/ci/global.yml
--- a/.gitlab/ci/global.yml
+++ b/.gitlab/ci/global.yml
@@ -28,7 +28,6 @@
   - poetry install
   - section_end "poetry-install"
 
-
 .setup-artifactory:
   - section_start "Setup Artifactory" --collapsed
   - chmod 700 ${ARTIFACTORY_SETUP_SCRIPT}
@@ -44,13 +43,21 @@
     fi
   - section_end "Create Artifacts"
 
+.create-artifacts-repositories-folder:
+  - section_start "Create Artifacts Repositories Folder" --collapsed
+  - |
+    if [[ ! -d "${CI_PROJECT_DIR}/artifacts/repositories" ]]; then
+      echo "Creating repositories folder:${CI_PROJECT_DIR}/artifacts/repositories"
+      mkdir -p -m 777 "${CI_PROJECT_DIR}/artifacts/repositories" # using the -p to create the folder hierarchy.
+    fi
+  - section_end "Create Artifacts Repositories Folder"
+
 .granting_execute_permissions_on_files:
   - section_start "Granting execute permissions on files" --collapsed
   - chmod +x ./Tests/scripts/*
   - chmod +x ./Tests/Marketplace/*
   - chmod +x ./SecretActions/SecretsBuild/*
   - section_end "Granting execute permissions on files"
-
 
 .check-is-force-merged-allowed:
   - section_start "Check is force merged allowed" --collapsed
@@ -70,6 +77,137 @@
       echo "The MR is not a force merge"
     fi
   - section_end "Check is force merged allowed"
+
+.clone-content-test-conf:
+  - section_start "Clone content test conf" --collapsed
+  - exec 3>&1 4>&2
+  - exec > >(tee -a "${ARTIFACTS_FOLDER}/logs/clone_demisto_content_test_conf.log") 2>&1
+  - |
+    set +e
+
+    RED='\033[0;31m'
+    GREEN='\033[0;32m'
+    BLUE='\033[0;34m'
+    NC='\033[0m'
+
+    clone_repository() {
+      local host=$1
+      local user=$2
+      local token=$3
+      local repo_name=$4
+      local branch=$5
+      local retry_count=$6
+      local sleep_time=${7:-10}  # default sleep time is 10 seconds.
+      local exit_code=0
+      local i=1
+      echo -e "${GREEN}Checking if repository project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name} already exists in ${CI_PROJECT_DIR}/artifacts/repositories/${repo_name}${NC}"
+      if [ -d "${CI_PROJECT_DIR}/artifacts/repositories/${repo_name}" ]; then
+        echo -e "${GREEN}Repository ${repo_name} already exists, no need to clone it again${NC}"
+        return 0
+      fi
+      echo -e "${GREEN}Cloning project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name} from ${host} branch:${branch} with ${retry_count} retries${NC}"
+      if [ -z "${user}" ] && [ -z "${token}" ]; then
+        user_info=""
+      else
+        user_info="${user}:${token}@"
+        # If either user or token is not empty, then we need to add them to the url.
+      fi
+      pushd "${CI_PROJECT_DIR}/artifacts/repositories" || exit 1
+      for ((i=1; i <= retry_count; i++)); do
+        git clone --depth=1 "https://${user_info}${host}/${CI_PROJECT_NAMESPACE}/${repo_name}.git" --branch "${branch}" && exit_code=0 && break || exit_code=$?
+        if [ ${i} -ne "${retry_count}" ]; then
+          echo -e "${RED}Failed to clone project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name} with branch:${branch}, exit code:${exit_code}, sleeping for ${sleep_time} seconds and trying again${NC}"
+          sleep "${sleep_time}"
+        else
+          echo -e "${RED}Failed to clone project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name} with branch:${branch}, exit code:${exit_code}, exhausted all ${retry_count} retries${NC}"
+          break
+        fi
+      done
+      popd || exit 1
+      return ${exit_code}
+    }
+
+    clone_repository_with_fallback_branch() {
+      local host=$1
+      local user=$2
+      local token=$3
+      local repo_name=$4
+      local branch=$5
+      local retry_count=$6
+      local sleep_time=${7:-10}  # default sleep time is 10 seconds.
+      local fallback_branch="${8:-master}"
+
+      # Check if branch exists in the repository.
+      echo -e "${GREEN}Checking if branch ${branch} exists in project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name}${NC}"
+      if [ -z "${user}" ] && [ -z "${token}" ]; then
+        user_info=""
+      else
+        # If either user or token is not empty, then we need to add them to the url.
+        user_info="${user}:${token}@"
+      fi
+      git ls-remote --exit-code --quiet --heads "https://${user_info}${host}/${CI_PROJECT_NAMESPACE}/${repo_name}.git" "refs/heads/${branch}" 1>/dev/null 2>&1
+      local branch_exists=$?
+
+      if [ "${branch_exists}" -ne 0 ]; then
+        echo -e "${RED}Branch ${branch} does not exist in project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name}, defaulting to ${fallback_branch}${NC}"
+        local exit_code=1
+      else
+        echo -e "${GREEN}Branch ${branch} exists in project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name}, trying to clone${NC}"
+        clone_repository "${host}" "${user}" "${token}" "${repo_name}" "${branch}" "${retry_count}" "${sleep_time}"
+        local exit_code=$?
+        if [ "${exit_code}" -ne 0 ]; then
+          echo -e "${RED}Failed to clone project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name} with branch:${branch}, exit code:${exit_code}${NC}"
+        fi
+      fi
+      if [ "${exit_code}" -ne 0 ]; then
+        # Trying to clone from fallback branch.
+        echo -e "${RED}Trying to clone  project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name} with fallback branch ${fallback_branch}!${NC}"
+        clone_repository "${host}" "${user}" "${token}" "${repo_name}" "${fallback_branch}" "${retry_count}" "${sleep_time}"
+        local exit_code=$?
+        if [ ${exit_code} -ne 0 ]; then
+          echo -e "${RED}ERROR: Failed to clone project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name} with fallback branch:${fallback_branch}, exit code:${exit_code}, exiting!${NC}"
+          exit ${exit_code}
+        else
+          echo -e "${GREEN}Successfully cloned project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name} with fallback branch:${fallback_branch}${NC}"
+          return 0
+        fi
+      else
+        echo -e "${GREEN}Successfully cloned project namespace:${CI_PROJECT_NAMESPACE} repository:${repo_name} with branch:${branch}${NC}"
+        return 0
+      fi
+    }
+    clone_repository_with_fallback_branch "${CI_SERVER_HOST}" "gitlab-ci-token" "${CI_JOB_TOKEN}" "content-test-conf" "${CI_COMMIT_REF_NAME}" 3 10 "master"
+
+    if [ ! -d "${CI_PROJECT_DIR}/config" ]; then mkdir -p "${CI_PROJECT_DIR}/config"; else echo "Directory ${CI_PROJECT_DIR}/config already exists"; fi
+    cp -r "${CI_PROJECT_DIR}/artifacts/repositories/content-test-conf/config/"* "${CI_PROJECT_DIR}/config/"
+
+    NAME_MAPPING_PATH="${CI_PROJECT_DIR}/config/name_mapping.json"
+    if [ ! -f "${NAME_MAPPING_PATH}" ]; then
+      echo "File ${NAME_MAPPING_PATH} does not exist, exiting!"
+      exit 1;
+    fi
+
+    XSIAM_SERVERS_PATH="${CI_PROJECT_DIR}/config/xsiam_servers.json"
+    if [ ! -f "${XSIAM_SERVERS_PATH}" ]; then
+      echo "File ${XSIAM_SERVERS_PATH} does not exist, exiting!"
+      exit 1;
+    fi
+    echo "${XSIAM_SERVERS_PATH}" > "${CI_PROJECT_DIR}/xsiam_servers_path"
+
+    XSOAR_NG_SERVERS_PATH="${CI_PROJECT_DIR}/config/xsoar_ng_servers.json"
+    if [ ! -f "${XSOAR_NG_SERVERS_PATH}" ]; then
+      echo "File ${XSOAR_NG_SERVERS_PATH} does not exist, exiting!"
+      exit 1;
+    fi
+    echo "${XSOAR_NG_SERVERS_PATH}" > "${CI_PROJECT_DIR}/xsoar_ng_servers_path"
+
+    set -e
+    echo "Successfully cloned content-test-conf repository"
+
+  - exec 1>&3 2>&4
+  - exec 3>&- 4>&-
+  - section_end "Clone content test conf"
+
 .docker_services:
   services:
     - name: ${DOCKER_IO}/library/docker:20.10.12-dind
